### ISSUE TITLE
Custom Fields

### ISSUE THREAD

**Issue by rohansood42** [adib2149/FormMaster#1]
I wanted to add a field of name is it possible to add? Or any other custom field which is not present in the Types?

**Comment by riddhimanadib** [comment]
**Currently, only the supported types are defined.** But if you want anything more to be implemented, you can do it in either of the following ways:

1. You can use the type `FormElement.TYPE_EDITTEXT_TEXT_SINGLELINE` to use as your field of name.
2. Add the type as an issue here, and I'll update the library with your required type.
3. You can make a Pull Request with your desired formatting. If it goes with our current prospect, I'll merge and add it.
4. Fork this project and modify as you want by yourself.
