### ISSUE TITLE
Doesnt get focus on itemview click

### ISSUE THREAD

**Issue by mihirsane** [adib2149/FormMaster#4]
The edittext needs to get focus on the item click event. User isnt able to understand where to click.

**Comment by riddhimanadib** [comment]
Hi, can you be a little more specific? Do you want the first form element to get focus when the form is displayed??

**Comment by mihirsane** [comment]
When I click on the element with an edittext I have to specifically click on the edit text area to make it focusable. Instead I would like to have a feature where the edittext is focussed even if I click on the label of the element. Check my fork to see the changes.

**Comment by riddhimanadib** [comment]
Great!! Do you plan to make a Pull Request? If you're adding the requested feature by yourself, let me know. Else I'll be adding it myself.

**Comment by mihirsane** [comment]
You may merge my changes to the master.

**Comment by riddhimanadib** [comment]
I accepted your merge request, but quite a few things were not as I thought of, so I changed them. Please look at them when you can. Thanks. This feature is now added.

**Comment by mihirsane** [comment]
Seems neat. Thank you.
